version: '3.8'

services:
  web:
    build: .
    ports:
      - "2000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ticketdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ticketdb.sql:/docker-entrypoint-initdb.d/ticketdb.sql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
